theme = "basic"
baseURL = "https://celedigital.github.io/"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true

[languages]
  [languages.es]
    languageName = "Español"
    languageCode = "es"
    contentDir = "content/es"
    weight = 1

    [languages.es.params]
      logo = "img/logo_cele.svg"
      mission = "Investigación, escritura y análisis sobre derecho, tecnología y gobernanza."

      [languages.es.params.mission_link]
        label = "Ver más"
        url = "/acerca-de/"

    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Nosotros"
        url = "/nosotros/"
        identifier = "nosotros"
        weight = 1

      [[languages.es.menu.main]]
        name = "Nuestra misión"
        url = "/mision/"
        parent = "nosotros"
        weight = 11

      [[languages.es.menu.main]]
        name = "Equipo"
        url = "/equipo/"
        parent = "nosotros"
        weight = 12

      [[languages.es.menu.main]]
        name = "Contacto"
        url = "/contacto/"
        parent = "nosotros"
        weight = 13

      [[languages.es.menu.main]]
        name = "temas"
        url = "/temas/"
        identifier = "temas"
        weight = 2

      [[languages.es.menu.main]]
        name = "Libertad de expresión"
        url = "/temas/libertad-de-expresion"
        parent = "temas"
        weight = 21

      [[languages.es.menu.main]]
        name = "Derechos Humanos"
        url = "/temas/derechos-humanos"
        parent = "temas"
        weight = 22

      [[languages.es.menu.main]]
        name = "Gobernanza de Internet"
        url = "/temas/gobernanza"
        parent = "temas"
        weight = 23

      [[languages.es.menu.main]]
        name = "Amenazas a la LDE"
        url = "/temas/amenazas"
        parent = "temas"
        weight = 24

      [[languages.es.menu.main]]
        name = "Inteligencia Artificial"
        url = "/temas/inteligencia-artificial"
        parent = "temas"
        weight = 25

      [[languages.es.menu.main]]
        name = "Privacidad y Vigilancia"
        url = "/temas/privacidad-y-vigilancia"
        parent = "temas"
        weight = 26

      [[languages.es.menu.main]]
        name = "investigaciones"
        url = "/investigaciones/"
        weight = 3

      [[languages.es.menu.main]]
        name = "policy"
        url = "/policy/"
        weight = 4

      [[languages.es.menu.main]]
        name = "observatorio legislativo"
        url = "/observatorio-legislativo/"
        weight = 5

      [[languages.es.menu.main]]
        name = "taller"
        url = "/taller/"
        weight = 6

      [[languages.es.menu.main]]
        name = "sala de prensa"
        url = "/sala-de-prensa/"
        weight = 7

  [languages.en]
    languageName = "English"
    languageCode = "en"
    contentDir = "content/en"
    weight = 2

    [languages.en.params]
      logo = "img/logo_cele.svg"
      mission = "Research, writing, and analysis on law, technology, and governance."

      [languages.en.params.mission_link]
        label = "Read more"
        url = "/about/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        url = "/about/"
        identifier = "about"
        weight = 1

      [[languages.en.menu.main]]
        name = "Mission"
        url = "/mission/"
        parent = "about"
        weight = 11

      [[languages.en.menu.main]]
        name = "Team"
        url = "/team/"
        parent = "about"
        weight = 12

      [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact/"
        parent = "about"
        weight = 13

      [[languages.en.menu.main]]
        name = "Topics"
        url = "/topics/"
        identifier = "topics"
        weight = 2

      [[languages.en.menu.main]]
        name = "Freedom of Expression in the 21st Century"
        url = "/topics/freedom-of-expression"
        parent = "topics"
        weight = 21

      [[languages.en.menu.main]]
        name = "Human Rights"
        url = "/topics/human-rights"
        parent = "topics"
        weight = 22

      [[languages.en.menu.main]]
        name = "Governance"
        url = "/topics/governance"
        parent = "topics"
        weight = 23

      [[languages.en.menu.main]]
        name = "Threats to Freedom of Expression"
        url = "/topics/threats"
        parent = "topics"
        weight = 24

      [[languages.en.menu.main]]
        name = "Artificial Intelligence"
        url = "/topics/artificial-intelligence"
        parent = "topics"
        weight = 25

      [[languages.en.menu.main]]
        name = "Privacy and Surveillance"
        url = "/topics/privacy-and-surveillance"
        parent = "topics"
        weight = 26

      [[languages.en.menu.main]]
        name = "Research"
        url = "/research/"
        weight = 3

      [[languages.en.menu.main]]
        name = "Policy"
        url = "/policy/"
        weight = 4

      [[languages.en.menu.main]]
        name = "Legislative Observatory"
        url = "/legislative-observatory/"
        weight = 5

      [[languages.en.menu.main]]
        name = "Workshop"
        url = "/workshop/"
        weight = 6

      [[languages.en.menu.main]]
        name = "Press Room"
        url = "/press-room/"
        weight = 7
